name: CI Training

on:
  push:
    branches:
      - main

env:
  API_IMAGE_NAME: quay.io/imenbenmansour01/titanic/api

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --group training --group dev --group api

      - name: Launch unit tests
        run: |
          uv run pytest tests/ci tests/training tests/api

      - name: Login to Quay
        run: |
          echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u "${{ vars.QUAY_USERNAME }}" --password-stdin

      - name: Build and push API image
        run: |
          docker build -f k8s/api/Dockerfile -t ${{ env.API_IMAGE_NAME }}:latest .
          docker push ${{ env.API_IMAGE_NAME }}:latest
